name: Auto Merge PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Wait for checks to pass
      uses: actions/github-script@v6
      with:
        script: |
          const pr = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
          });

          if (pr.data.mergeable && pr.data.mergeable_state === "clean") {
            console.log("The PR is mergeable.");
          } else {
            throw new Error("PR is not mergeable yet.");
          }

    - name: Auto-merge the PR
      uses: actions/github-script@v6
      with:
        script: |
          await github.rest.pulls.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
            merge_method: 'squash'  # Change 'squash' to 'merge' or 'rebase' as needed
          });
