name: Auto Merge PR

on:
  pull_request:
    types: [opened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Check if the PR was created by bot
      id: check
      run: |
        # Check if the PR title follows the expected pattern (from the update action)
        if [[ "${{ github.event.pull_request.title }}" == *"[🤖] Update"* ]]; then
          echo "::set-output name=should_merge::true"
        else
          echo "::set-output name=should_merge::false"
    
    - name: Auto-merge the PR
      if: steps.check.outputs.should_merge == 'true'
      uses: actions/github-script@v6
      with:
        script: |
          github.pulls.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
            merge_method: 'squash'
          })
